name = "HasagawaWakatini"
uuid = "77b4a5b0-6ed9-4abb-b852-b72faee8deaf"
authors = ["JohannesMorkrid <johannes.morkrid@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
